version: "3.8"

services:
  node:
    image: node:20
    volumes:
      - .:/home/app:cached
      - node_modules:/home/app/node_modules
    working_dir: /home/app
    tty: true

volumes:
  node_modules:
